### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by creydr**
Updating dependencies to latest, as dependency bump in CI has some hiccup: https://github.com/knative-sandbox/knobots/actions/runs/5306811278/jobs/9604767562

### CODE REVIEW

**Comment by creydr** [comment]
Need the updates from https://github.com/knative/eventing/pull/7029 too
/hold

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
@pierDipi could you recheck on this PR? I had to fix some linting issues this morning.

**Pull request merged**
