### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by creydr**
As per title

### CODE REVIEW

**Comment by creydr** [comment]
/hold
to check first if #55 is enough to unblock the release

**Comment by dsimansk** [comment]
@creydr the diff looks like it's already moving beyond `release-1.11` and taking it on `main`. What cmd did you used to update?

**Comment by creydr** [comment]
> @creydr the diff looks like it's already moving beyond `release-1.11` and taking it on `main`. What cmd did you used to update?

```
./hack/update-deps.sh --upgrade
```

**Comment by pierDipi** [comment]
> > @creydr the diff looks like it's already moving beyond `release-1.11` and taking it on `main`. What cmd did you used to update?
> 
> ```
> ./hack/update-deps.sh --upgrade
> ```

you need the version there `--release v1.11`

**Comment by creydr** [comment]
> > > @creydr the diff looks like it's already moving beyond `release-1.11` and taking it on `main`. What cmd did you used to update?
> > 
> > 
> > ```
> > ./hack/update-deps.sh --upgrade
> > ```
> 
> you need the version there `--release v1.11`

Ah ok :+1:

**Pull request closed without merging**
